remote_theme           : "just-the-docs/just-the-docs"
repository             : "sdpa-python/sdpa-python.github.io"
title                  : "SDPA for Python"
description            : "Python 3 Wrapper for SDPA (SemiDefinite Programming Algorithm)"
color_scheme           : "celestite"

plugins:
  - jekyll-sitemap
  - jekyll-include-cache

whitelist:
  - jekyll-sitemap
  - jekyll-include-cache

callouts:
  attention:
    color: blue

  warning:
    color: red

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sdpa-python/sdpa-python.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
